"use server";

import { revalidatePath } from "next/cache";

import { requireSession } from "@/lib/auth";
import type { EarnedBadge } from "@/lib/badges";
import { getPendingBadges } from "@/lib/data";
import { supabase } from "@/lib/supabase";

export type PendingAnswer = {
  /** Generated on the client before sending, so a retry is recognisable. */
  eventId: string;
  questionId: string;
  wasCorrect: boolean;
};

/**
 * Record answers idempotently. The client owns the event ids, so a queue that
 * retries after a failure — or after a refresh — cannot count an answer twice.
 * Returns the ids the server accepted, which is every id it has now seen,
 * including ones it had already stored, so the client can clear its queue.
 *
 * Learn also gets the badges still waiting to be celebrated. They are read after
 * the write rather than taken from it, so a badge whose earlier response was
 * lost is returned here too. Quizzes never receive them: they are held back for
 * the results screen.
 */
export async function recordAnswers(
  answers: PendingAnswer[],
  source: "learn" | "quiz" = "learn",
): Promise<{ acknowledged: string[]; pendingBadges: EarnedBadge[] }> {
  const session = await requireSession();
  if (answers.length === 0) return { acknowledged: [], pendingBadges: [] };

  const { error } = await supabase().rpc("record_answers_once", {
    p_profile_id: session.profileId,
    p_answers: answers.map((a) => ({
      event_id: a.eventId,
      question_id: a.questionId,
      correct: a.wasCorrect,
    })),
    p_source: source,
  });
  if (error) throw new Error(error.message);

  // A failure to read badges must not make the client think its answers were
  // not saved, so it degrades to "nothing to celebrate right now".
  const pendingBadges =
    source === "learn" ? await getPendingBadges(session.profileId).catch(() => []) : [];

  return { acknowledged: answers.map((a) => a.eventId), pendingBadges };
}

export type SubmittedQuizAnswer = {
  /** Stable per attempt+question, so a resubmission is not counted twice. */
  eventId: string;
  questionId: string;
  questionText: string;
  correctAnswer: string;
  explanation: string | null;
  selectedAnswer: string | null;
  wasCorrect: boolean;
};

/**
 * Persist a finished quiz and fold its answers into mastery, so the "missed"
 * and "unmastered" question pools stay accurate after a quiz.
 * Returns the attempt id for the review screen.
 */
/**
 * Persist a finished quiz. `attemptId` is generated by the client when the quiz
 * starts, so resubmitting after a failed request reuses the same row instead of
 * creating a second attempt, and the answers are replaced rather than appended.
 */
export async function submitQuiz(
  deckId: string,
  answers: SubmittedQuizAnswer[],
  startedAt: string,
  attemptId?: string,
): Promise<string> {
  const session = await requireSession();
  const db = supabase();

  if (attemptId) {
    const { data: existing } = await db
      .from("quiz_attempts")
      .select("id, completed_at")
      .eq("id", attemptId)
      .maybeSingle();
    // Already graded: hand back the same attempt rather than scoring it twice.
    if (existing?.completed_at) return existing.id;
  }

  const score = answers.filter((a) => a.wasCorrect).length;
  const total = answers.length;
  const percentage = total > 0 ? Math.round((score / total) * 10000) / 100 : 0;

  const { data: attempt, error: attemptError } = await db
    .from("quiz_attempts")
    .upsert({
      ...(attemptId ? { id: attemptId } : {}),
      deck_id: deckId,
      profile_id: session.profileId,
      score,
      total_questions: total,
      percentage,
      started_at: startedAt,
      // Deliberately not completed yet. It is marked complete only once the
      // answers and the mastery updates have both landed, so a failure here
      // leaves a retry able to finish the job rather than short-circuiting on
      // an attempt that merely looks done.
      completed_at: null,
    })
    .select("id")
    .single();
  if (attemptError) throw new Error(attemptError.message);

  // A retry re-writes the answer rows rather than doubling them.
  await db.from("quiz_answers").delete().eq("quiz_attempt_id", attempt.id);

  if (answers.length > 0) {
    const { error: answersError } = await db.from("quiz_answers").insert(
      answers.map((answer, index) => ({
        quiz_attempt_id: attempt.id,
        question_id: answer.questionId,
        question_text: answer.questionText,
        correct_answer: answer.correctAnswer,
        explanation: answer.explanation,
        selected_answer: answer.selectedAnswer,
        was_correct: answer.wasCorrect,
        position: index,
      })),
    );
    if (answersError) throw new Error(answersError.message);

    // Unanswered questions are left out of mastery entirely rather than
    // counted as misses. Event ids are derived from the attempt so a retry
    // cannot apply the same answer to mastery twice.
    const attempted = answers.filter((a) => a.selectedAnswer !== null);
    if (attempted.length > 0) {
      const { error: progressError } = await db.rpc("record_answers_once", {
        p_profile_id: session.profileId,
        p_answers: attempted.map((a) => ({
          event_id: a.eventId,
          question_id: a.questionId,
          correct: a.wasCorrect,
        })),
        p_source: "quiz",
      });
      if (progressError) throw new Error(progressError.message);
    }
  }

  // Everything is stored; only now does the attempt count as finished.
  const { error: finishError } = await db
    .from("quiz_attempts")
    .update({ completed_at: new Date().toISOString() })
    .eq("id", attempt.id);
  if (finishError) throw new Error(finishError.message);

  return attempt.id;
}

/**
 * Wipe this profile's learning progress for one deck: mastery, accuracy,
 * miss counts and therefore its review flags all go back to zero.
 *
 * Stars are deliberately left alone — they are manual bookmarks, not progress.
 * The answer_events ledger is also kept: it is what makes retries idempotent,
 * and clearing it would let a queued answer replay into the fresh slate.
 */
export async function resetDeckProgress(deckId: string): Promise<void> {
  const session = await requireSession();
  const db = supabase();

  const { data: questions, error } = await db.from("questions").select("id").eq("deck_id", deckId);
  if (error) throw new Error(error.message);

  const ids = (questions ?? []).map((q) => q.id);
  // Chunked because the ids travel in the query string.
  for (let i = 0; i < ids.length; i += 50) {
    const batch = ids.slice(i, i + 50);
    const { error: deleteError } = await db
      .from("question_progress")
      .delete()
      .eq("profile_id", session.profileId)
      .in("question_id", batch);
    if (deleteError) throw new Error(deleteError.message);
  }

  revalidatePath(`/decks/${deckId}`);
}
