"use server";

import { requireSession } from "@/lib/auth";
import { supabase } from "@/lib/supabase";

/** Record one Learn answer. Any signed-in profile may do this. */
export async function recordAnswer(questionId: string, wasCorrect: boolean): Promise<void> {
  const session = await requireSession();
  const { error } = await supabase().rpc("record_answer", {
    p_profile_id: session.profileId,
    p_question_id: questionId,
    p_correct: wasCorrect,
  });
  if (error) throw new Error(error.message);
}

export type PendingAnswer = {
  /** Generated on the client before sending, so a retry is recognisable. */
  eventId: string;
  questionId: string;
  wasCorrect: boolean;
};

/**
 * Record answers idempotently. The client owns the event ids, so a queue that
 * retries after a failure — or after a refresh — cannot count an answer twice.
 * Returns the ids the server accepted, which is every id it has now seen,
 * including ones it had already stored, so the client can clear its queue.
 */
export async function recordAnswers(
  answers: PendingAnswer[],
  source: "learn" | "quiz" = "learn",
): Promise<{ acknowledged: string[] }> {
  const session = await requireSession();
  if (answers.length === 0) return { acknowledged: [] };

  const { error } = await supabase().rpc("record_answers_once", {
    p_profile_id: session.profileId,
    p_answers: answers.map((a) => ({
      event_id: a.eventId,
      question_id: a.questionId,
      correct: a.wasCorrect,
    })),
    p_source: source,
  });
  if (error) throw new Error(error.message);

  return { acknowledged: answers.map((a) => a.eventId) };
}

export type SubmittedQuizAnswer = {
  /** Stable per attempt+question, so a resubmission is not counted twice. */
  eventId: string;
  questionId: string;
  questionText: string;
  correctAnswer: string;
  explanation: string | null;
  selectedAnswer: string | null;
  wasCorrect: boolean;
};

/**
 * Persist a finished quiz and fold its answers into mastery, so the "missed"
 * and "unmastered" question pools stay accurate after a quiz.
 * Returns the attempt id for the review screen.
 */
/**
 * Persist a finished quiz. `attemptId` is generated by the client when the quiz
 * starts, so resubmitting after a failed request reuses the same row instead of
 * creating a second attempt, and the answers are replaced rather than appended.
 */
export async function submitQuiz(
  deckId: string,
  answers: SubmittedQuizAnswer[],
  startedAt: string,
  attemptId?: string,
): Promise<string> {
  const session = await requireSession();
  const db = supabase();

  if (attemptId) {
    const { data: existing } = await db
      .from("quiz_attempts")
      .select("id, completed_at")
      .eq("id", attemptId)
      .maybeSingle();
    // Already graded: hand back the same attempt rather than scoring it twice.
    if (existing?.completed_at) return existing.id;
  }

  const score = answers.filter((a) => a.wasCorrect).length;
  const total = answers.length;
  const percentage = total > 0 ? Math.round((score / total) * 10000) / 100 : 0;

  const { data: attempt, error: attemptError } = await db
    .from("quiz_attempts")
    .upsert({
      ...(attemptId ? { id: attemptId } : {}),
      deck_id: deckId,
      profile_id: session.profileId,
      score,
      total_questions: total,
      percentage,
      started_at: startedAt,
      completed_at: new Date().toISOString(),
    })
    .select("id")
    .single();
  if (attemptError) throw new Error(attemptError.message);

  // A retry re-writes the answer rows rather than doubling them.
  await db.from("quiz_answers").delete().eq("quiz_attempt_id", attempt.id);

  if (answers.length > 0) {
    const { error: answersError } = await db.from("quiz_answers").insert(
      answers.map((answer, index) => ({
        quiz_attempt_id: attempt.id,
        question_id: answer.questionId,
        question_text: answer.questionText,
        correct_answer: answer.correctAnswer,
        explanation: answer.explanation,
        selected_answer: answer.selectedAnswer,
        was_correct: answer.wasCorrect,
        position: index,
      })),
    );
    if (answersError) throw new Error(answersError.message);

    // Unanswered questions are left out of mastery entirely rather than
    // counted as misses. Event ids are derived from the attempt so a retry
    // cannot apply the same answer to mastery twice.
    const attempted = answers.filter((a) => a.selectedAnswer !== null);
    if (attempted.length > 0) {
      const { error: progressError } = await db.rpc("record_answers_once", {
        p_profile_id: session.profileId,
        p_answers: attempted.map((a) => ({
          event_id: a.eventId,
          question_id: a.questionId,
          correct: a.wasCorrect,
        })),
        p_source: "quiz",
      });
      if (progressError) throw new Error(progressError.message);
    }
  }

  return attempt.id;
}
